name: Coverage Test

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: golang:1.24
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests with coverage
        run: |
          go test ./... -coverprofile=coverage.out -covermode=atomic

      - name: Get PR Coverage
        run: |
          COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
          echo "Current PR coverage: $COVERAGE%"

      - name: Checkout base branch
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          git checkout ${{ github.base_ref }}

      - name: Run tests on base branch
        run: |
          go test ./... -coverprofile=coverage_base.out -covermode=atomic

      - name: Get Base Branch Coverage
        run: |
          BASE_COVERAGE=$(go tool cover -func=coverage_base.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
          echo "BASE_COVERAGE=$BASE_COVERAGE" >> $GITHUB_ENV
          echo "Base branch coverage: $BASE_COVERAGE%"

      - name: Check coverage threshold
        run: |
          if (( $(echo "$COVERAGE < $BASE_COVERAGE" | bc -l) )); then
            echo "Coverage is lower than the base branch! Failing the job."
            exit 1
          fi
          echo "Coverage is equal or greater than the base branch. ✅"

